eureka:
  client:
    register-with-eureka: false
server:
  port:8080

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: Inventory
          uri: 'http://microServices:8083'
          predicates:
            - Path=/api/inventory/**
        - id: Product
          uri: 'http://localhost:8084'
          predicates:
            - Path=/demo/product/**
